### ISSUE TITLE
Feature request: pretty printing of XML output

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-apps#119]
Applies to VeraPDF 0.26.16.

Not a big deal really, but it would be nice to have the possibility to produce pretty-printed XML output, either as an option or by default (applies to both CLI and GUI).

**Comment by carlwilson** [comment]
This has been caused by the change to a new XML output stream class that's no longer honouring the formatted output from JAXB. There are a couple of standard "fixes" suggested, usually they use a wrapper stream that inserts line and indents as required. We have a similar wrapper that handles the indentation that IS working. @BezrukovM would you please take a look at the possibility of better indentation, but as a low priority activity.
