### ISSUE TITLE
verapdf.bat and verapdf-gui.bat fail if space in JAVACMD (windows)

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-apps#216]
The line

`%JAVACMD% %JAVA_OPTS%  -classpath %CLASSPATH% -Dfile.encoding=UTF8 -Dapp.name="VeraPDF validation GUI" -Dapp.repo="%REPO%" -Dapp.home="%BASEDIR%" -Dbasedir="%BASEDIR%" org.verapdf.cli.VeraPdfCli %CMD_LINE_ARGS%`

fails if JAVACMD is set like this

`set JAVACMD=C:\Program Files\Java\jre1.8.0_141\bin\java`

solution:
in both files, put quotes when %JAVACMD% is called, i.e. make it

`"%JAVACMD%" %JAVA_OPTS%  -classpath %CLASSPATH% -Dfile.encoding=UTF8 -Dapp.name="VeraPDF validation GUI" -Dapp.repo="%REPO%" -Dapp.home="%BASEDIR%" -Dbasedir="%BASEDIR%" org.verapdf.cli.VeraPdfCli %CMD_LINE_ARGS%`

**Comment by carlwilson** [comment]
Hi @THausherr 

Please could you let me know the version of Windows and Java you're using please?

Thanks

**Comment by carlwilson** [comment]
I've managed to reproduce this on a Win7 VM and have submitted a fix #224 

The latest dev version contains the fix and can be downloaded here: http://software.verapdf.org/develop/verapdf-installer.zip if you'd like to test it. I'll close this when the release comes out unless you get in touch to say otherwise.

Thanks again

**Comment by THausherr** [comment]
Works fine, thank you!
