### ISSUE TITLE
v0.20.3 CLI :~$ ./verapdf -x <pdf> # does not produce a feature report?

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-apps#55]
Expected result: detailed information about the PDF -file (no validation).

Actual result: (validation)
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-08-17T18:34:40.352Z" processingTime="00:00:02.555">
    <itemDetails size="284635">
        <name>/data/v/veraPDF/0.20.3/./testfiles/2013/tecken.MO03.AR10.1.7.pdf</name>
    </itemDetails>
    <validationReport profile="PDF/A-1B validation profile" compliant="false">
        <statement>PDF file is not compliant with Validation Profile requirements.</statement>
        <details passedRules="102" failedRules="1" passedChecks="9032" failedChecks="1">
            <rule specification="ISO 19005-1:2005" clause="6.3.5" testNumber="1" status="failed" passedChecks="305" failedChecks="1">
                <description>The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, 
                        except when the fonts are used exclusively with text rendering mode 3.</description>
                <object>Glyph</object>
                <test>renderingMode == 3 || isGlyphPresent == true</test>
                <check status="failed">
                    <context>root/document[0]/pages[0](1 0 obj PDPage)/contentStream[0](238 0 obj PDContentStream)/operators[342]/usedGlyphs[0](POPFKP+Wingdings3 0 0)</context>
                </check>
            </rule>
        </details>
    </validationReport>
    <pdfFeaturesReport/>
</report>
```
Using the GUI:
- Report type: Features
- (Flavour) PDF/A-1a

output:
```
<report creationDate="2016-08-17T18:50:39.915Z" processingTime="00:00:00.129">
    <itemDetails size="284635">
        <name>/data/v/veraPDF/0.20.3/testfiles/2013/tecken.MO03.AR10.1.7.pdf</name>
    </itemDetails>
    <pdfFeaturesReport/>
</report>
```

**Comment by BezrukovM** [comment]
1) About "no validation". In case of using only -x option, veraPDF app will still validation file since default flavour (option -f) value is "auto". Hence "./verapdf -x <pdf>" is equal to "./verapdf -x -f auto <pdf>"
2) About missed features report. Actually it works normally. In 0.20 release we have added features configuration file (which is placed by path config/features.xml in application folder) in which user can specify necessary features. By the default all features are disabled and hence we will obtain empty features report.
In #57 I have changed default values for features configuration file (now Information Dictionary features are enabled in it by default) and introduced additional features configuration panel for GUI (shows by using menu: File - Features Config) in which you can easy change features configuration properties (also, that changes wright onto features.xml file).
In case of using CLI you still have to change that file by yourself.
